x-airflow-common:
  &airflow-common
  build: dockerfiles/airflow
  env_file:
    - ./.env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
  volumes:
    - ./dag_configs:/opt/airflow/dag_configs
    - ./dags:/opt/airflow/dags
    - airflow_logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      POSTGRES_MULTIPLE_DATABASES: airflow, mlflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./scripts/postgres_init_script:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: on-failure

  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: on-failure

  minio:
    container_name: minio-container
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "airflow"
      MINIO_ROOT_PASSWORD: "airflow123"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure


  mc-service:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-container:9000 airflow airflow123;
      /usr/bin/mc mb myminio/airflow;
      /usr/bin/mc mb myminio/mlflow;
      /usr/bin/mc mb myminio/lizvladi-mlops;
      /usr/bin/mc anonymous  set public myminio/airflow;
      /usr/bin/mc anonymous  set public myminio/mlflow;
      /usr/bin/mc anonymous  set public myminio/lizvladi-mlops;
      "


  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
        mkdir -p /sources /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - .:/sources


  airflow-jupyter:
    <<: *airflow-common
    container_name: airflow_jupyter
    command: bash -cx "jupyter notebook --ip 0.0.0.0
            --NotebookApp.token='airflow' --no-browser --allow-root"
    ports:
      - 8888:8888
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  ml_flow:
    <<: *airflow-common
    container_name: ml_flow
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    command: bash -cx  "mlflow server --host 0.0.0.0
              --backend-store-uri postgresql://test:test@postgres:5432/mlflow
      --default-artifact-root s3://mlflow --serve-artifacts"

volumes:
  postgres-db-volume:
  airflow_logs:
